apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-deployment
  namespace: godo
  labels:
    app: forum
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      # serviceAccountName: find-endpoints
      containers:
      - name: forum-container
        image: forum:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 150m
            memory: 50Mi
          limits:
            cpu: 300m
            memory: 100Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      # 或者用podpreset
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: forum-svc
  namespace: godo
spec:
  ports:
    - nodePort: 32101
      port: 8000  # cluster
      protocol: TCP
      targetPort: 8000  # pod
  type: NodePort
  selector:
    app: forum
